### ISSUE TITLE
can't run '/usr/bin/linuxpba': No such file or directory

### ISSUE THREAD

**Issue by brianjmurrell** [cranderson/buildroot-linuxpba#2]
I tried to build your PBA buildroot image here and when built, I installed it but when I rebooted I got the error message:

`can't run '/usr/bin/linuxpba': No such file or directory`

**Comment by cranderson** [comment]
This should be fixed now.  A modified package/Config.in with msed added needs to be used.  I've now made that modified Config.in file part of this tree.

**Comment by cranderson** [comment]
I've now also uploaded a pre-built msedlinuxpba.img.  This version also fixes issues with non-standard USB keyboards.
